export const ONE_SECOND_MILISECONDS = 1000
export const ONE_MINUTE_MILISECONDS = ONE_SECOND_MILISECONDS * 60
export const ONE_MINUTE_SECONDS = 60
export const ONE_HOUR_MILISECONDS = ONE_MINUTE_MILISECONDS * 60
export const ONE_HOUR_SECONDS = ONE_MINUTE_SECONDS * 60
export const ONE_DAY_MILISECONDS = ONE_HOUR_MILISECONDS * 24;
export const ONE_DAY_SECONDS = ONE_HOUR_SECONDS * 24;

